import zmq, zmq.auth
from zmq.auth.thread import ThreadAuthenticator

import ai_google_gemini as ai
from search_image import *
import webbrowser

print("\nHello.\n")
print("\"Enter\" key to begin.")
if input() != "":
    quit()
print("\nWhat is the username :\n")
username = input()
print("\nEnter your password:\n")
password = input()

ctx = zmq.Context.instance()
auth = ThreadAuthenticator(ctx)
auth.start()
auth.allow("127.0.0.1")
auth.configure_curve(domain = "*", location = ".")
client = ctx.socket(zmq.REQ)
client_public, client_secret = zmq.auth.load_certificate("client_transfer.key_secret")
client.curve_secretkey = client_secret
client.curve_publickey = client_public
server_public, _ = zmq.auth.load_certificate("server_transfer.key")
client.curve_serverkey = server_public
client.connect("tcp://127.0.0.1:1398")

profile_authentication = (username + " " + password).encode()
client.send(profile_authentication)

if client.poll(10000):
    if client.recv().decode() != "success":
        print("Incorrect username and password. Please try again later.")
        exit()

undo = ""

print(f"\nHello, {username}, let's begin. What would you like to see/read?\n\nThe program will describe something you want to know about.\n\n"
      "Additionally, the program will show you an image you want to see.\n\n"
      "Text generated by program will be displayed in console window.\n\n"
      "Image generated from program will be displayed in your browser.\n\n"
      "Results will only show after hitting \"Enter\" button.\n")
response = input()
print()

while response != "close":
    if response == "redo":
        response = undo
    else:
        response = response.lower()
        undo = response
    if ("image" in response or "picture" in response or "see" in response or "show" in response):
        response = response.split(" ", maxsplit = 1)[1]
        image = show_image(response)
        webbrowser.open_new(image)
    else:
        print(ai.knowledge(response))
    print("Would you like to see/read anything else? Results will only show after hitting \"Enter\" button.\n"
          "Close software with \"close\" + \"Enter\" button.\nTo redo previous search, type \"redo\" + \"Enter\" button.")
    print()
    response = input()
    print()

auth.stop()
print("Completed log out.\n")
print(f"See you, {username}.")